// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gjjqSKbRqXuaUimkLf8eMG
// Component: q4FPf_vi5_PT2a

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { GHLink } from "../../../../components/Link/Link"; // plasmic-import: Y3ppP90YtTpcYt/codeComponent
import { GHImage } from "../../../../components/Image/Image"; // plasmic-import: QSbPt8k9Nh7KxW/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_gh_demo.module.css"; // plasmic-import: gjjqSKbRqXuaUimkLf8eMG/projectcss
import sty from "./PlasmicGhLogoLink.module.css"; // plasmic-import: q4FPf_vi5_PT2a/css

export type PlasmicGhLogoLink__VariantMembers = {};
export type PlasmicGhLogoLink__VariantsArgs = {};
type VariantPropType = keyof PlasmicGhLogoLink__VariantsArgs;
export const PlasmicGhLogoLink__VariantProps = new Array<VariantPropType>();

export type PlasmicGhLogoLink__ArgsType = {};
type ArgPropType = keyof PlasmicGhLogoLink__ArgsType;
export const PlasmicGhLogoLink__ArgProps = new Array<ArgPropType>();

export type PlasmicGhLogoLink__OverridesType = {
  root?: p.Flex<typeof GHLink>;
  ghImage?: p.Flex<typeof GHImage>;
};

export interface DefaultGhLogoLinkProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicGhLogoLink__RenderFunc(props: {
  variants: PlasmicGhLogoLink__VariantsArgs;
  args: PlasmicGhLogoLink__ArgsType;
  overrides: PlasmicGhLogoLink__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <GHLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      href={"https://driver.grubhub.com" as const}
      target={"_blank" as const}
    >
      <GHImage
        data-plasmic-name={"ghImage"}
        data-plasmic-override={overrides.ghImage}
        alt={"logo-image" as const}
        backgroundColor={``}
        backgroundImage={"" as const}
        className={classNames("__wab_instance", sty.ghImage)}
        height={"50px" as const}
        src={
          "https://res.cloudinary.com/grubhub-marketing/image/upload/v1628272845/HERMES/Logos/2021%20Citrus%20Updates/2-B2B/Grubhub%20For%20Drivers/LOGO-GFD-Horizontal-Citrus.png" as const
        }
        width={"500px" as const}
      />
    </GHLink>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "ghImage"],
  ghImage: ["ghImage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof GHLink;
  ghImage: typeof GHImage;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGhLogoLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGhLogoLink__VariantsArgs;
    args?: PlasmicGhLogoLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGhLogoLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicGhLogoLink__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGhLogoLink__ArgProps,
          internalVariantPropNames: PlasmicGhLogoLink__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicGhLogoLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGhLogoLink";
  } else {
    func.displayName = `PlasmicGhLogoLink.${nodeName}`;
  }
  return func;
}

export const PlasmicGhLogoLink = Object.assign(
  // Top-level PlasmicGhLogoLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    ghImage: makeNodeComponent("ghImage"),

    // Metadata about props expected for PlasmicGhLogoLink
    internalVariantProps: PlasmicGhLogoLink__VariantProps,
    internalArgProps: PlasmicGhLogoLink__ArgProps
  }
);

export default PlasmicGhLogoLink;
/* prettier-ignore-end */
